## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [4]:
import numpy as np

In [8]:
def create_array_to_zero(N):
    return np.arange(N-1,-1,-1)

create_array_to_zero(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [13]:
def create_matrix_to_zero(N):
    return np.diag(create_array_to_zero(N), k=0)
    
m = create_matrix_to_zero(10)
print(m)
sum(m[i][i] for i in range(len(m)))

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


45

## Задание 3
Решите систему уравнений: <br>
4x + 2y + z = 4 <br>
x + 3y = 12 <br>
5y + 4z = -3 <br>


In [16]:
from numpy import linalg

In [17]:
a = np.array( [[4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [18]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True